### ISSUE TITLE
Implement Ball Tele-Control Power-Up

### ISSUE THREAD

**Issue by lucashmorais** [phrb/BrickBreaker#26]
Implement power up for allowing the player to exert a field force over the ball with the slider.

**Comment by phrb** [comment]
@lucashmorais try to assign a milestone and update issue #17 with new issues! :smiley: 

Also, especially for power-up/down issues, remember to update issue #4.

Maybe issue #4 should be completed first, to standardize how power-ups/downs are implemented. Then new issues could implement different types. @lucashmorais, I assigned you to that issue as well, but we can work together on this. What do you think @lucaskanashiro?

**Comment by lucaskanashiro** [comment]
It works for me, for now I am working on "game support" stuff (menu) and win condition.

**Comment by phrb** [comment]
There is still a bug in pull request #29
